name: Build on push

on: [push]

jobs:
  build:
    name: Build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup VSWhere.exe
      uses: warrenbuckley/Setup-VSWhere@v1

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Nuget Restore 
      run: nuget restore .\WorkflowTest\WorkflowTest.sln

    - name: Build Solution 
      run: powershell -Command " $msbuild = vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe;  & "$msbuild" .\WorkflowTest\WorkflowTest.sln "

    - name: Debug
      uses: ninjaoxygen/debug-action@v1

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: cpz
        path: WorkflowTest\WorkflowTestProgram\bin\Release\WorkflowTestProgram.cpz
