name: Build on push

on: [push]

jobs:
  build:
    name: Build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Nuget Restore 
      run: nuget restore .\WorkflowTest\WorkflowTest.sln

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build Solution 
      run: msbuild.exe .\WorkflowTest\WorkflowTest.sln -p:Configuration=Release

    - name: Get a directory listing
      run: powershell -Command " Get-ChildItem -Recurse | Out-File dir.txt "

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: cpz
        path: WorkflowTest\WorkflowTestProgram\bin\Release\WorkflowTestProgram.cpz
